# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
# Copy AzureDeploy Files To Staging Directory
- task: CopyFiles@2
  inputs:
    Contents: '**\AzureDeploy\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Build Database Project Into Dacpac
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.Database.csproj'
    arguments: '--output $(Build.ArtifactStagingDirectory)'

# Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'ReactWebsiteArtifact'
